In [1]:
from sklearn import datasets
iris = datasets.load_iris() # 분꽃 데이터셋
#digits = datasets.load_digits() # 숫자 데이터셋
#diabetes = datasets.load_diabetes() # 당뇨 데이터셋
#bcancer = datasets.load_breast_cancer() # 폐암

In [2]:
from sklearn.model_selection._split import train_test_split

x = iris.data[:, :3] # feature
y = iris.target  # label, class

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state = 0)

In [4]:
print(x_train)

[[5.  2.  3.5]
 [6.5 3.  5.5]
 [6.7 3.3 5.7]
 [6.  2.2 5. ]
 [6.7 2.5 5.8]
 [5.6 2.5 3.9]
 [7.7 3.  6.1]
 [6.3 3.3 4.7]
 [5.5 2.4 3.8]
 [6.3 2.7 4.9]
 [6.3 2.8 5.1]
 [4.9 2.5 4.5]
 [6.3 2.5 5. ]
 [7.  3.2 4.7]
 [6.5 3.  5.2]
 [6.  3.4 4.5]
 [4.8 3.1 1.6]
 [5.8 2.7 5.1]
 [5.6 2.7 4.2]
 [5.6 2.9 3.6]
 [5.5 2.5 4. ]
 [6.1 3.  4.6]
 [7.2 3.2 6. ]
 [5.3 3.7 1.5]
 [4.3 3.  1.1]
 [6.4 2.7 5.3]
 [5.7 3.  4.2]
 [5.4 3.4 1.7]
 [5.7 4.4 1.5]
 [6.9 3.1 4.9]
 [4.6 3.1 1.5]
 [5.9 3.  5.1]
 [5.1 2.5 3. ]
 [4.6 3.4 1.4]
 [6.2 2.2 4.5]
 [7.2 3.6 6.1]
 [5.7 2.9 4.2]
 [4.8 3.  1.4]
 [7.1 3.  5.9]
 [6.9 3.2 5.7]
 [6.5 3.  5.8]
 [6.4 2.8 5.6]
 [5.1 3.8 1.6]
 [4.8 3.4 1.6]
 [6.5 3.2 5.1]
 [6.7 3.3 5.7]
 [4.5 2.3 1.3]
 [6.2 3.4 5.4]
 [4.9 3.  1.4]
 [5.7 2.5 5. ]
 [6.9 3.1 5.4]
 [4.4 3.2 1.3]
 [5.  3.6 1.4]
 [7.2 3.  5.8]
 [5.1 3.5 1.4]
 [4.4 3.  1.3]
 [5.4 3.9 1.7]
 [5.5 2.3 4. ]
 [6.8 3.2 5.9]
 [7.6 3.  6.6]
 [5.1 3.5 1.4]
 [4.9 3.1 1.5]
 [5.2 3.4 1.4]
 [5.7 2.8 4.5]
 [6.6 3.  4.4]
 [5.  3.2 1.2]
 [5.1 3.3 

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# scaling(표준화)
print(x_train[:3])
sc = StandardScaler()
sc.fit(x_test)
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)  # 표준화 완성
print(x_train[:3])

# 표준화 값을 원래 값으로 복귀
# inver_x_train = sc.inverse_transform(x_train)
# print(inver_x_train[:3])

In [2]:
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
#(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
#(x_train, y_train), (x_test, y_test) = tf.keras.datasets.boston_housing.load_data()


57026/57026 [==============================] - 0s 0us/step
