In [50]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

bcancer = datasets.load_breast_cancer()

data = bcancer.data
target = bcancer.target

train_input, test_input, train_target, test_target = train_test_split(data,target,random_state=42)

In [51]:
train_input.shape

(426, 30)

In [52]:
train_target.shape

(426,)

In [53]:
# 이진 분류

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(train_input)
train_input = sc.transform(train_input)

In [54]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(30,)))
model.add(layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 16)                496       
                                                                 
 dense_11 (Dense)            (None, 1)                 17        
                                                                 
Total params: 513 (2.00 KB)
Trainable params: 513 (2.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [55]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [56]:
model.fit(train_input,train_target, epochs=10, batch_size=100)

Epoch 1/10
5/5 [==============================] - 1s 26ms/step - loss: 0.5210 - accuracy: 0.7535
Epoch 2/10
5/5 [==============================] - 0s 9ms/step - loss: 0.4035 - accuracy: 0.8568
Epoch 3/10
5/5 [==============================] - 0s 8ms/step - loss: 0.3502 - accuracy: 0.8967
Epoch 4/10
5/5 [==============================] - 0s 8ms/step - loss: 0.3118 - accuracy: 0.9108
Epoch 5/10
5/5 [==============================] - 0s 7ms/step - loss: 0.2834 - accuracy: 0.9225
Epoch 6/10
5/5 [==============================] - 0s 8ms/step - loss: 0.2599 - accuracy: 0.9296
Epoch 7/10
5/5 [==============================] - 0s 8ms/step - loss: 0.2406 - accuracy: 0.9319
Epoch 8/10
5/5 [==============================] - 0s 7ms/step - loss: 0.2240 - accuracy: 0.9366
Epoch 9/10
5/5 [==============================] - 0s 7ms/step - loss: 0.2098 - accuracy: 0.9413
Epoch 10/10
5/5 [==============================] - 0s 7ms/step - loss: 0.1967 - accuracy: 0.9413


In [57]:
sc.fit(test_input)
test_input = sc.transform(test_input)

In [58]:
model.evaluate(test_input,test_target)

5/5 [==============================] - 0s 14ms/step - loss: 0.1522 - accuracy: 0.9580


[0.15219028294086456, 0.9580419659614563]

In [59]:
from sklearn import datasets

diabetes = datasets.load_diabetes()

data = diabetes.data
target = diabetes.target

In [60]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data,target,random_state=42)

In [61]:
train_input.shape

(331, 10)

In [62]:
train_target.shape

(331,)

In [63]:
# 회귀
# 전처리

from sklearn.preprocessing import StandardScaler

sc= StandardScaler()
sc.fit(train_input)
train_input = sc.transform(train_input)

In [64]:
train_target = train_target.reshape((-1,1))
sc1 = StandardScaler()
sc1.fit(train_target)
train_target = sc1.transform(train_target)

In [65]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential()
model.add(layers.Dense(6, activation='relu', input_shape=(10,)))
model.add(layers.Dense(1, activation='linear'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 6)                 66        
                                                                 
 dense_13 (Dense)            (None, 1)                 7         
                                                                 
Total params: 73 (292.00 Byte)
Trainable params: 73 (292.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [66]:
model.compile(optimizer='rmsprop', loss='mse', metrics='mae')

In [67]:
model.fit(train_input, train_target, epochs=20)

Epoch 1/20
11/11 [==============================] - 0s 11ms/step - loss: 3.0618 - mae: 1.4038
Epoch 2/20
11/11 [==============================] - 0s 6ms/step - loss: 2.6785 - mae: 1.3144
Epoch 3/20
11/11 [==============================] - 0s 6ms/step - loss: 2.4055 - mae: 1.2459
Epoch 4/20
11/11 [==============================] - 0s 6ms/step - loss: 2.1791 - mae: 1.1852
Epoch 5/20
11/11 [==============================] - 0s 6ms/step - loss: 1.9824 - mae: 1.1304
Epoch 6/20
11/11 [==============================] - 0s 6ms/step - loss: 1.8082 - mae: 1.0808
Epoch 7/20
11/11 [==============================] - 0s 6ms/step - loss: 1.6442 - mae: 1.0287
Epoch 8/20
11/11 [==============================] - 0s 6ms/step - loss: 1.5037 - mae: 0.9832
Epoch 9/20
11/11 [==============================] - 0s 6ms/step - loss: 1.3804 - mae: 0.9454
Epoch 10/20
11/11 [==============================] - 0s 6ms/step - loss: 1.2643 - mae: 0.9054
Epoch 11/20
11/11 [==============================] - 0s 6ms/step - l

In [68]:
from sklearn import datasets
digits = datasets.load_digits()

data = digits.data
target = digits.target

In [69]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data,target,random_state=42)

In [70]:
train_input.shape

(1347, 64)

In [71]:
train_target.shape

(1347,)

In [72]:
# 문제 : 다항분류

In [73]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler

train_target = to_categorical(train_target)

sc = StandardScaler()
sc.fit(train_input)
train_input = sc.transform(train_input)

In [74]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(64,)))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [75]:
print(train_input)

[[ 0.         -0.34658389 -0.67111503 ... -1.15783495 -0.50770266
  -0.19895848]
 [ 0.          5.19793507  2.23828434 ... -0.13881915 -0.26774635
  -0.19895848]
 [ 0.         -0.34658389 -0.25548655 ... -0.81816302 -0.50770266
  -0.19895848]
 ...
 [ 0.         -0.34658389  0.78358465 ...  1.55954051 -0.02779004
  -0.19895848]
 [ 0.         -0.34658389 -0.87892927 ... -1.15783495 -0.50770266
  -0.19895848]
 [ 0.         -0.34658389 -0.87892927 ... -0.98799898 -0.50770266
  -0.19895848]]


In [76]:
print(train_target)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [77]:
model.fit(train_input,train_target, epochs=10)

Epoch 1/10
43/43 [==============================] - 1s 24ms/step - loss: 2.1039 - accuracy: 0.3073
Epoch 2/10
43/43 [==============================] - 0s 11ms/step - loss: 1.5205 - accuracy: 0.5731
Epoch 3/10
43/43 [==============================] - 0s 10ms/step - loss: 1.1782 - accuracy: 0.6682
Epoch 4/10
43/43 [==============================] - 0s 9ms/step - loss: 0.9397 - accuracy: 0.7335
Epoch 5/10
43/43 [==============================] - 0s 10ms/step - loss: 0.7605 - accuracy: 0.7988
Epoch 6/10
43/43 [==============================] - 0s 10ms/step - loss: 0.6196 - accuracy: 0.8478
Epoch 7/10
43/43 [==============================] - 0s 10ms/step - loss: 0.5090 - accuracy: 0.8753
Epoch 8/10
43/43 [==============================] - 1s 13ms/step - loss: 0.4245 - accuracy: 0.9013
Epoch 9/10
43/43 [==============================] - 0s 10ms/step - loss: 0.3626 - accuracy: 0.9191
Epoch 10/10
43/43 [==============================] - 0s 10ms/step - loss: 0.3161 - accuracy: 0.9272
